//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3074
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetupExample {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetupExample.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fertig ähnelt.
        /// </summary>
        internal static string Dialog_Finish {
            get {
                return ResourceManager.GetString("Dialog_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter &gt; ähnelt.
        /// </summary>
        internal static string Dialog_Next {
            get {
                return ResourceManager.GetString("Dialog_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; Zurück ähnelt.
        /// </summary>
        internal static string Dialog_Previous {
            get {
                return ResourceManager.GetString("Dialog_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup ähnelt.
        /// </summary>
        internal static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        internal static string InstallPath_ButtonBrowseText {
            get {
                return ResourceManager.GetString("InstallPath_ButtonBrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Pfad ist ungültig. ähnelt.
        /// </summary>
        internal static string InstallPath_ErrorboxText {
            get {
                return ResourceManager.GetString("InstallPath_ErrorboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiger Pfad ähnelt.
        /// </summary>
        internal static string InstallPath_ErrorboxTitle {
            get {
                return ResourceManager.GetString("InstallPath_ErrorboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation abbrechen ähnelt.
        /// </summary>
        internal static string InstallStep_CancelCaption {
            get {
                return ResourceManager.GetString("InstallStep_CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll die Installation wirklich abgebrochen werden? Beim Abbrechen der Installation wird die installierte Software vollständig vom System entfernt. ähnelt.
        /// </summary>
        internal static string InstallStep_CancelText {
            get {
                return ResourceManager.GetString("InstallStep_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Software wird installiert... ähnelt.
        /// </summary>
        internal static string InstallStep_Install {
            get {
                return ResourceManager.GetString("InstallStep_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Software wird entfernt... ähnelt.
        /// </summary>
        internal static string InstallStep_Uninstall {
            get {
                return ResourceManager.GetString("InstallStep_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annehmen ähnelt.
        /// </summary>
        internal static string LicenseStep_AcceptButtonText {
            get {
                return ResourceManager.GetString("LicenseStep_AcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen beim Setup ähnelt.
        /// </summary>
        internal static string UninstallStep_Headline {
            get {
                return ResourceManager.GetString("UninstallStep_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorhandene Installation überschreiben ähnelt.
        /// </summary>
        internal static string UninstallStep_ReinstallText {
            get {
                return ResourceManager.GetString("UninstallStep_ReinstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Assistent wird Software entfernen oder reparieren. ähnelt.
        /// </summary>
        internal static string UninstallStep_Text {
            get {
                return ResourceManager.GetString("UninstallStep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deinstallieren ähnelt.
        /// </summary>
        internal static string UninstallStep_UninstallText {
            get {
                return ResourceManager.GetString("UninstallStep_UninstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen beim Setup ähnelt.
        /// </summary>
        internal static string WelcomeStep_Headline {
            get {
                return ResourceManager.GetString("WelcomeStep_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Assistent wird Software auf dem System installieren.
        ///Vor der Installation müssen Sie dem Lizenzvertrag zustimmen. ähnelt.
        /// </summary>
        internal static string WelcomeStep_WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeStep_WelcomeText", resourceCulture);
            }
        }
    }
}
